import { notFound } from "next/navigation";
import { getAppContext } from "@/lib/data";
import { formatMoney,formatClubDateTime } from "@/lib/format";
import { PrintButton } from "@/components/print-button";

export const metadata={title:"Receipt"};export const dynamic="force-dynamic";
export default async function ReceiptPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const {supabase,club}=await getAppContext();
  const [{data:order},{data:footerSetting}]=await Promise.all([supabase.from("orders").select("*,snooker_tables(name),profiles!orders_created_by_fkey(full_name),order_items(*),payments(*)").eq("id",id).single(),supabase.from("club_settings").select("value").eq("key","receipt_footer").maybeSingle()]);if(!order)notFound();
  const footer=typeof footerSetting?.value==="string"&&footerSetting.value?footerSetting.value:`Thank you for visiting ${club.name}.`;
  return <><div className="page-head no-print"><div><h1 className="page-title">Receipt #{order.order_number}</h1></div><PrintButton/></div><article className="receipt"><div className="receipt-brand">{club.name}</div><div>Qeilvra Snooker Club Management</div><div className="receipt-rule"/><div className="receipt-meta"><span>Order</span><strong>#{order.order_number}</strong><span>Date</span><strong>{formatClubDateTime(order.created_at,club.timezone)}</strong><span>Staff</span><strong>{order.profiles?.full_name}</strong><span>Table</span><strong>{order.snooker_tables?.name??"Counter"}</strong></div><div className="receipt-rule"/>{order.order_items.map((item:{id:string;product_name:string;quantity:number;unit_price:number;total_price:number})=><div className="receipt-line" key={item.id}><span>{item.quantity} × {item.product_name}</span><strong>{formatMoney(item.total_price,club.currency)}</strong></div>)}<div className="receipt-rule"/><div className="receipt-line"><span>Products</span><strong>{formatMoney(order.subtotal,club.currency)}</strong></div>{Number(order.table_charge)>0&&<div className="receipt-line"><span>Table charge</span><strong>{formatMoney(order.table_charge,club.currency)}</strong></div>}{Number(order.discount_amount)>0&&<div className="receipt-line"><span>Discount</span><strong>−{formatMoney(order.discount_amount,club.currency)}</strong></div>}<div className="receipt-line receipt-total"><span>Total</span><strong>{formatMoney(order.total_amount,club.currency)}</strong></div><div className="receipt-rule"/>{order.payments.map((payment:{id:string;payment_method:string;amount:number})=><div className="receipt-line" key={payment.id}><span style={{textTransform:"capitalize"}}>{payment.payment_method}</span><strong>{formatMoney(payment.amount,club.currency)}</strong></div>)}<div className="receipt-rule"/><p>{footer}</p></article></>;
}
