import { getAppContext } from "@/lib/data";
import { can } from "@/lib/permissions";
import { formatClubDateTime, formatMoney } from "@/lib/format";
import { EmptyState } from "@/components/empty-state";
import { CategoryForm, ProductForm, StockForm } from "@/components/inventory-forms";
import type { Product } from "@/types/domain";

export const metadata={title:"Inventory"};export const dynamic="force-dynamic";
export default async function InventoryPage(){const{supabase,club,profile}=await getAppContext();const[{data:productsData},{data:categoriesData},{data:history}]=await Promise.all([supabase.from("products").select("*,product_categories(name)").order("name"),supabase.from("product_categories").select("id,name").eq("is_active",true).order("sort_order"),supabase.from("inventory_transactions").select("*,products(name),profiles!inventory_transactions_created_by_fkey(full_name)").order("created_at",{ascending:false}).limit(30)]);const products=(productsData??[]) as Product[];const categories=(categoriesData??[]) as {id:string;name:string}[];return <><div className="page-head"><div><h1 className="page-title">Inventory</h1><p className="page-subtitle">Products, prices and auditable stock levels.</p></div></div><section className="panel">{products.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.product_categories?.name}</td><td>{formatMoney(p.price,club.currency)}</td><td>{p.stock_quantity}</td><td><span className={`badge ${p.stock_quantity<=p.low_stock_threshold?"red":"green"}`}>{p.stock_quantity<=p.low_stock_threshold?"Low stock":"In stock"}</span></td></tr>)}</tbody></table></div>:<EmptyState title="No products found."/>}</section>{can(profile.role,"inventory.manage")&&<div className="management-forms"><ProductForm categories={categories}/><StockForm products={products}/><CategoryForm/></div>}<section className="panel" style={{marginTop:14}}><div className="panel-head"><h2 className="panel-title">Stock history</h2></div>{history?.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Time</th><th>Product</th><th>Type</th><th>Change</th><th>Balance</th><th>Staff</th></tr></thead><tbody>{history.map(item=><tr key={item.id}><td>{formatClubDateTime(item.created_at,club.timezone)}</td><td>{item.products?.name}</td><td>{item.transaction_type}</td><td style={{color:item.quantity>=0?"var(--green)":"var(--red)"}}>{item.quantity>0?"+":""}{item.quantity}</td><td>{item.new_quantity}</td><td>{item.profiles?.full_name}</td></tr>)}</tbody></table></div>:<EmptyState title="No stock movements recorded."/>}</section></>}
